# Introducción {#intro}

La Universidad Nacional de Colombia (UNAL), ente rector de la educación superior de Colombia, consciente de la necesidad de fortalecer los procesos de producción y difusión de la información estadística, así como de responder de una manera más adecuada a los requerimientos de información de la academia, las instituciones nacionales e internacionales, la comunidad universitaria y de la propia entidad, y considerando que la poca visibilización de la información es uno de los puntos neurálgicos de la gestión pública, ha tomado la iniciativa de formular un Plan Estadístico Institucional.

Este ejercicio se soporta conceptualmente de los lineamientos metodológicos del Departamento Administrativo Nacional de Estadistica, DANE, que según el decreto 4178 de 2012 tiene entre sus funciones la planificación, estandarización y certificación de las estadísticas. Parafraseando al @BibEntry2021Apr, un Plan Estadístico institucional es un instrumento de determinación y priorización de la información estadística y demás resultados que se requieren o desean generar en un ámbito institucional; éste contiene la información estratégica que se requiere para la formulación de políticas públicas, la planeación, la toma de decisiones, así como para la evaluación y el seguimiento a los planes misionales y de acción.

Es así como en el marco del proyecto del Fortalecimiento Estadístico de la Universidad - fase I y bajo la orientación de la Dirección Nacional de Planeación y Estadística, se busca visibilizar la información institucional generada - oferta -, evaluar los niveles de satisfacción de información demandada por las dependencias del nivel nacional e identificar los procesos de gestión de la información.

Este ejercicio de planificación estadística obedece a la necesidad de definir, organizar y priorizar la información estadística que requiere la Universidad, en función de solucionar los problemas de desconocimiento y baja utilización de la información producida, entre otros factores que configuran un tratamiento inadecuado de la información generada por las diferentes dependencias que componen la Universidad.

En consecuencia, la elaboración de un Plan Estadístico institucional para la UNAL, se constituye en una estrategia tanto para facilitar los procesos de toma de decisiones como para hacer más efectivos los mecanismos de rendición de cuentas a la ciudadanía, a partir de un mayor y mejor aprovechamiento de la información generada, avanzando con ello en el fortalecimiento de la transparencia, la honestidad y el control social efectivo e incluyente sobre la gestión adelantada.

Como este instrumento, se espera lograr reducir los requerimientos no satisfechos de información que se presentan en la Universidad, por lo menos en los que respecta al componente estratégico de la información estadística, en la medida en que se definirán las estadísticas que son prioritarias para dar cuenta del que hacer de la entidad en relación con los componentes de Investigación, Extensión, Admisión y Movilidad, entre otros.

El documentos que se presenta a continuación está conformado por la descripción de la metodología para elaborar el Plan Estadístico de la UNAL; el diagnóstico de la actividad estadística en la Universidad, según cada uno de los ejes temáticos de información estadística; los resultados del cruce de oferta y demanda de información estadística en la UNAL; la formulación de la parte estratégica del Plan Estadístico UNAL, el Plan de Acción Institucional y, por último, los anexos correspondientes a los metadatos de las operaciones estadísticas que resumen la oferta de estadísticas estratégicas de la UNAL. El inventario de información se construyó conjuntamente con los delegados de las áreas y dependencias entre los meses de octubre de 2016 y julio de 2017.


