# El Plan Estadístico

El Plan Estadístico es básicamente una herramienta que identifica, organiza, depura, prioriza y difunde la información estratégica que se requiere para la formulación de políticas, la planeación y
toma de decisiones, y para la evaluación y seguimiento a los procesos y procedimientos; teniendo
en cuenta esta definición, el objetivo del plan es entonces “Organizar los procesos de producción y
de gestión de la información estadística de la entidad, de modo que se constituya en un soporte
eficiente para la formulación de políticas públicas, la planeación, la toma de decisiones, el
seguimiento y la evaluación de los planes misionales”.

El plan tiene como uno de sus productos principales la generación de un inventario de
información, que contiene las fichas técnicas de las operaciones estadísticas, es decir, la
caracterización de los procesos en los cuales existe una captura de datos, procesamiento y análisis,
y generación información estadística (agregados estadísticos o indicadores). Se asume que la
información estadística es el conjunto de resultados cuantitativos que se obtienen mediante el
tratamiento sistemático de datos que se originan en encuestas, censos o mediante la
consolidación de registros, para la medición y estudio de fenómenos de interés. Los datos son las
unidades de información que incluyen percepciones, números, observaciones, hechos y cifras,
pero que al estar desligadas de un contexto particular carecen de sentido informativo.

La necesidad de contar con una herramienta que permitiera regular la producción y el uso de la
información estadística para su mejor aprovechamiento, y que además posibilite la coordinación y
participación de productores y usuarios, ha llevado a varios países e instituciones a desarrollar
planes estadísticos por su utilidad en cuanto a reducir requerimientos estadísticos, y aportar a la
organización y articulación de sistemas de información, han sido adoptados e implementados con
mayor fuerza en la Unión Europea y la Comunidad Andina.

El Plan Estadístico Nacional de España ha sido el de mayor reconocimiento por su continuidad y
continuo crecimiento desde el año 2009, estando actualmente vinculado al Real Decreto
1017/2013, de 20 de diciembre para su cumplimiento y regulación, por el que se aprueba el Programa anual 2014 del Plan Estadístico Nacional 2013-2016. De igual manera otras comunidades
de España como Cataluña y Andalucía, y en países de América como México, Uruguay, Perú, Chile
y Colombia han implementado sus planes estadísticos Nacionales.

A nivel Nacional, se han implementado planes en las corporaciones regionales de Cundinamarca,
Antioquia, Norte de Santander, Boyacá y Bucaramanga. Otras instituciones que los han
implementado son la Policía Nacional de Colombia, la Superintendencia de la Economía Solidaria,
el Consejo Superior de la Judicatura, Coldeportes, y finalmente el Plan Estadístico Nacional, como
parte de las acciones definidas por el SEN (Sistema Estadístico Nacional) todos ellos con la asesoría
técnica o elaboración directa del DANE.

En el año 2001, el DANE desarrollo una metodología para la planificación estadística, actualizada
en el 2007, que responde a las necesidades planteadas por los territorios, sectores y entes
gubernamentales frente a la organización y manejo de la información disponible para la toma de
decisiones y la formulación de planes y proyectos de desarrollo. Esta metodología es la guía para la
formulación del Plan Estadístico institucional de la Universidad Nacional de Colombia, no obstante,
como resultado de las mesas técnicas adelantadas con funcionarios de las áreas misionales de la
universidad y reuniones de trabajo con el equipo de la Dirección de Planeación y Estadística, se
han hecho adaptaciones y complementado dicha metodología.
