# Plan de acción {#Cap6} 

### *Línea Estratégica I:* Lineamientos conceptuales y metodológicos

* *Objetivo específico 1:*

  Construir **LINEAMIENTOS CONCEPTUALES** que orienten
       la actividad estadística en la Universidad y que aporten al fortalecimiento de la producción estadística a nivel nacional e internacional.
  
  * *Acción 1:*
    
    **Desarrollar elementos conceptuales** que sirvan de referencia para la actividad estadística a nivel institucional y en el contexto nacional e internacional.

    * *Línea de base:*
      
      Libro: [Gestión de la información cuantitativa en las universidades](https://estadisticaun.github.io/L_Conceptual/).
    
    * *Comentarios:*
    
      Tener en cuenta dentro del estado del arte que ya se cuenta con un documento inicial de marco conceptual, ¿se podría cambiar la estrategía a socializar?
  
  * *Acción 2:*
  
    Estudiar el **uso potencial y alcance de técnicas contemporáneas** para el análisis de la información estadística institucional con propósitos explicativos, evaluativos o predictivos. 
  
    * *Comentario Nivel 1:*

      Técnicas contemporáneas: minería o analítica de datos, estadística, ciencia de los datos, big data, inteligencia de negocios.
  
  * *Acción 3:*    
  
    **Establecer el marco conceptual** y alcance para el monitoreo y seguimiento a planes, programas y proyectos institucionales a través de la construcción de indicadores desde una perspectiva cuantitativa.
  
    * *Comentarios:*
    
      Es importante desarrollarlo en el Plan II, teniendo en cuenta el proceso de formulación y desarrollo del PLEI.
  
  * *Acción 4:*    

    **Aportar a la definición de los elementos conceptuales y metodológicos que sirvan de referencia** para el desarrollo de evaluaciones a políticas, planes y proyectos institucionales desde una perspectiva cuantitativa.
  
    * *Comentarios:*
    
      Es importante acotar los documentos conceptuales y metodológicos de acuerdo con el uso de la información estadística (perspectiva cuantitativa).
    
      * *Acción nivel 2:*
      
        Realizar un estado del arte de las técnicas y metodologías empleadas para la evaluación de las políticas en el ámbito de la educación. 

* *Objetivo específico 2:*

  Definir y construir **INSTRUMENTOS METODOLÓGICOS** que apoyen
       el desarrollo de la actividad estadística.
  
  * *Acción 1:*
  
    **Definir y construir una guía metodológica** para el desarrollo y gestión de las **estadísticas oficiales** institucionales.
  
  * *Acción 2:*
  
    **Definir y construir una guía metodológica** que orienten la construcción de **indicadores de los procesos** en la Universidad.
  
    * *Acción nivel 2:*
    
      Actualizar la guía para la construcción de indicadores de proceso. 
  
  * *Acción 3:*
  
    Definir y construir una **guía metodológica para el seguimiento y monitoreo** a través de indicadores de planes, programas y proyectos institucionales.
  
  * *Acción 4:*
  
    Aportar al desarrollo de un **documento metodológico para la evaluación** de políticas, planes, programas  y proyectos institucionales.
  
  
### *Línea Estratégica II:* Producción estadística


* *Objetivo específico 3:* 
  
  Definir, adoptar o adaptar un marco orientador para la definición del **PROCESO ESTADÍSTICO** requerido para la producción de estadísticas oficiales.

 * *Acción 1:*
    
    Definir y adptar el **marco orientador** para la implementación del **proceso estadístico** a nivel institucional.

    * *Línea de base:*
      
      [Norma Técnica de Calidad del Proceso Estadístico - NTCPE 1000](https://www.dane.gov.co/files/sen/normatividad/NTC-Proceso-Estadistico-PE-1000-2020.pdf)
        
  * *Acción 2:*
  
    **Implementar y documentar el proceso estadístico** que soporta las operciones estadísticas requeridas para la producción de la información estadística oficial
    
 
 * *Objetivo específico 4:* 
  
  Fortalecer los **mecanismos de construcción y disposición** de las **ESTADÍSTICAS E INDICADORES**  oficiales institucionales
 
  * *Acción 1:*
  
    **Aumentar gradualmente,** a través de un ejercicio de priorización, la producción de **estadísticas e indicadores oficiales institucionales**. 


    *Acciones nivel 2:*
    
    - Definir un mecanismo institucional para la priorización en la construcción y publicación de estadísticas oficiales.

* *Acción 2:*
  
    Fortalecer los mecanismos de **difusión y comunicación** de las estadísticas oficiales e indicadores institucionales


    *Acciones nivel 2:*
    
    - Fortalecer, de manera continua,  la página web de [estadísticas oficiales](http://estadisticas.unal.edu.co/home/) de la Universidad
    - Definir e implementar estrategias innovadoras en materia de difusión de la información estadística institucional
    
* *Acción 3:*
  
    Fortalecer los niveles de **transparencia y apertura de los datos estadísticos** disponibles a nivel institucional.


    *Acciones nivel 2:*
    
    - Revisar los componentes jurídicos requeridos para la apertura de datos (leyes de transparencia y de Habeas Data)
    - Revisar las condiciones requeridas para la publicación de datos institucionales de manera abierta en el [portal de datos abiertos del estado colombiano](https://datos.gov.co/) 
    

* *Acción 4:*
  
    Fortalecer los niveles de **calidad, gobernabilidad y estandarización** de la producción estadística institucional.


    *Acciones nivel 2:*
    
    - Definir e implementar acciones encaminadas a aumentar los niveles de de calidad estadística en la captura, procesamiento, almacenamiento y difusión de la información estadística estratégica institucional.
    - Gestionar la certificación de calidad en la producción estadística oficial institucional ante los organismos nacionales en materia estadística.


* *Objetivo específico 5:* 
  
  Fomentar la realización de **ESTUDIOS E INVESTIGACIONES** a partir de los datos disponibles a nivel institucional.
 
  * *Acción 1:*
  
    Definir e iniciar la fase de implementación de **estudios e investigaciones** asociados a problemáticas institucionales a partir de los conjuntos de datos disponibles.         
        
        
### *Línea Estratégica III:* Gestión de las capacidades técnicas y tecnológicas. 


* *Objetivo específico 6:* 
  
  Definir, adquirir, construir, adaptar o configurar las **HERRAMIENTAS Y PLATAFORMAS TECNOLÓGICAS** requeridas  a nivel de software y hardware para la gestión estadística.  
  
  * *Acción 1:*
      
    **Definir, adquirir, adaptar y configurar las tecnologías y plataformas** adecuadas a **nivel de hardware** para la captura, producción, procesamiento, análisis y difusión de información estadística estratégica.

  * *Acción 2:*
    
    **Definir, adquirir y dominar los softwares requeridos** a nivel institucional para la captura, producción, procesamiento, análisis y difusión de información estadística estratégica
    
  * *Acción 3:*
  
  **Construir herramientas tecnológicas a nivel de software** que faciliten la disposición de estadísticas e indicadores institucionales


* *Objetivo específico 7:* 
  
  Fortalecer **LAS COMPETENCIAS TÉCNICAS/ACADÉMICAS** requeridas en el talento humano para la **gestión estadística** a nivel instiutucional..  
  
  * *Acción 1:*
      
    Establecer las **competencias mínimas requeridas a nivel técnico y tecnológico** para la gestión de información estadística.  

  * *Acción 2:*
      
    Definir e implementar un **plan de formación que fortalezca en los funcionarios** las competencias mínimas requeridas, especialmente a nivel técnico y tecnológico, en los procesos de consolidación, procesamiento, análisis y difusión de información estadística institucional. 
    

* *Objetivo específico 8:* 
  
  Aportar en la generación y construcción de **DIRECTRÍCES TÉCNICAS** a nivel de **software y hardware** para la gestión estadística institucional  
  
  * *Acción 1:*
      
    Aportar en la generación de **directrices técnicas en materia de adquisición de hardware y software** requerido para la gestíon estadística insitucional.      


### *Línea Estratégica IV:* Cultura estadística


* *Objetivo específico 9:* 

  **Promover la DIFUSIÓN y CONOCIMIENTO** de la información estadística oficial institucional. 
  
    * *Acción 1:* 
    
      **Socializar**, entre los integrantes de la comunidad universitaria, los distintos mecanismos que tiene la Universidad para la difusión de la información estadística oficial institucional.
      
    * *Acción 2:* 
    
      Proponer estrategias innovadoras que involucren el **uso de TICs con el objetivo de difundir la información estadística estratégica institucional.**
      
    * *Acción 3:* 
    
      Definir e implementar acciones que promuevan la **difusión de la información estadística oficial a nivel nacional e internacional**.
      
      * *Comentarios:*
      
        Difundir estadísticas relevantes de la Universidad a través de redes sociales (Trabajar este punto con Unimedios).


* *Objetivo específico 10:*

  Promover el **USO Y APROVECHAMIENTO DE LOS DATOS, ESTADÍSTICAS E INDICADORES** como activo estratégico institucional.
  
  * *Acción 1:*
  
    Desarrollar estrategias que promuevan el **uso de la información estadística** estratégica para la **toma de decisiones, la planeación institucional, la transparencia y la rendición permanente de cuentas.**.
    
    * *Comentarios:*
    
      Rendición de cuentas, informes de gestión,  Plan Global de Desarrollo y planes de acción, Acreditación Institucional,entre otros.
      
        * *Acción nivel 2:*
        
          Fomentar la incorporación de estadísticas oficiales e indicadores en los distintos mecanismos que tiene la Universidad para difundir los resultados de la gestión institucional.
      
  * *Acción 2:*
  
    **Fomentar, a nivel interno, el conocimiento y valoración del potencial estadístico** de la información consolidada a nivel institucional mediante registros administrativos.
    
    * *Acción nivel 2:*
    
      Identificar registros administrativos con potencial estadístico en la generación de nuevas estadísticas e indicadores.
      
  * *Acción 3:* 
  
    Construir y fomentar el uso de **cursos o espacios virtuales**  para fomentar el uso y aprovechamiento del valor contenido en los datos institucionales.
    

      
      
      
      
    
      
