# Conclusiones

Un ejercicio de planificación estadística como el realizado por la Universidad Nacional, es pertinente en la medida en que permita identificar las oportunidades de mejora en términos de la calidad de la producción estadística. Calidad definida por el grado de satisfacción que reporta el usuario final en términos de oportunidad, accesibilidad, transparencia, coherencia, continuidad y naturalmente pertinencia del producto estadístico.

Es importante sensibilizar a funcionarios y contratistas de la Universidad sobre la importancia estratégica de la información generada o recopilada en el desarrollo de los procesos estratégicos, misionales, de apoyo y de evaluación y mejora, toda vez, que si esta cumple con los criterios de calidad adecuados, se constituye en un factor clave para la toma de decisiones y para la asignación eficiente de los recursos disponibles. En ese sentido, es necesario reforzar el argumento que la información es un activo de la Universidad y por tanto debe estar disponible en condiciones adecuadas de calidad y oportunidad,  para el uso y aprovechamiento óptimo de quienes la demanden.

Un elemento clave para garantizar los flujos de información de manera oportuna en la Universidad, implica la comunicación entre los diferentes sistemas de información adoptados y actualmente en funcionamiento. De manera que la información referente a contratos, convenios, proyectos e información institucional  en general, se pueda consultar como un solo universo de análisis. De no adoptarse medidas correctivas en esta materia se seguiría fortaleciendo la compartimentación y fraccionamiento de la información.

Otro elemento esencial para el aprovechamiento y manejo adecuado de la información, se refiere a la definición y adopción de lineamientos claros en materia de codificación, almacenamiento, procesamiento y seguridad de la información, por parte de los funcionarios o contratistas responsables del manejo y procesamiento de información en las diferentes dependencias.

Finalmente, cabe resaltar que para que el ejercicio de planificación estadística adelantado, no se quede como otra de las múltiples iniciativas que se quedan en formulación, es necesario, en primer lugar socializar los resultados y recomendaciones consolidados en este documento y posteriormente  iniciar la implementación  de manera gradual pero continua, de todas  las acciones planteadas y validadas  en la matriz de intervención propuesta.